language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

branches:
  except:
    - /^v|d\d+\.\d+\.\d+$/

before_install:
  - sudo apt-get install -y realpath

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
 - cp ./auto-travis-install.xml ./jhove-installer/target/
 - MVN_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.3.1:exec)
 - java -jar ./jhove-installer/target/jhove-xplt-installer-$MVN_VERSION.jar auto-travis-install.xml
 - ~/jhove/jhove
 - ./jhove-bbt/scripts/travis-test.sh
