name: PR QA

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        java-version: [8, 11]

    steps:
      - uses: actions/checkout@v3
      - name: JDK setup
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots install -DjacocoAgg
      - name: Integration Tests
        if: matrix.java-version == 8
        run: ./bbt-jhove
        shell: bash
      - name: Aggregate integration test results
        if: matrix.java-version == 8
        run: mvn --batch-mode verify -DjacocoAgg
      - name: Upload coverage report
        if: matrix.java-version == 8
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: jhove-apps/target/site/jacoco-aggregate/
  coverage:
    name: Quality Assurance
    runs-on: ubuntu-20.04
    needs: [ build ]

    steps:
      - name: Download coverage report
        if: matrix.java-version == 8
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: core/target/site/jacoco/
      - name: Codecov coverage reporting
        if: matrix.java-version == 8
        uses: codecov/codecov-action@v3
        with:
          files: jhove-apps/target/site/jacoco-aggregate/jacoco.xml
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - name: Codacy coverage reporting
        uses: codacy/codacy-coverage-reporter-action@v1
        if: matrix.java-version == 8
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: jhove-apps/target/site/jacoco-aggregate/jacoco.xml
      - name: Codacy analysis reporting
        if: matrix.java-version == 8
        uses: codacy/codacy-analysis-cli-action@4.2.0
